- name: Configuring Jenkins agent
  hosts: jenkins-agents
  become: true
  tasks:
    - name: Installing openjdk
      yum:
        name: java-1.8.0-openjdk
        state: present
    
    - name: Creating apps directory
      file:
        path: /opt/apps
        state: directory
        mode: '0755'

    - name: Downloading Maven 3.6.3
      get_url:
        url: https://apache.osuosl.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
        dest: /opt/apps/maven363.tgz

    - name: Extracting the package
      unarchive:
        src: /opt/apps/maven363.tgz
        dest: /opt/apps/
        mode: '0755'
        remote_src: yes

